version: '3.3'

services:
        db:
                platform: linux/x86_64
                image: mysql:latest
                environment:
                        MYSQL_ROOT_PASSWORD: root
                ports:
                        - 3306:3306
                cap_add:
                        - SYS_NICE  # CAP_SYS_NICE to fix errors like mbind operation not permitted

