name: automate-newsletter-project-deploy
on:
  push:
    branches:
      - automate_deploy
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    
    - name: Create a python dist
      run: |
        cd newsletter_automation
        python ./setup.py sdist
        
    - name: Copy required scripts
      run: |
        echo "${{ secrets.CHESS_DB_KEY }}" > secret.pem
        chmod 400 secret.pem
        scp -o StrictHostKeyChecking=no -i secret.pem dist/newsletter-automation-0.1-1.tar.gz ubuntu@15.207.110.45:/home/ubuntu
        scp -o StrictHostKeyChecking=no -i secret.pem requirements.txt ubuntu@15.207.110.45:/home/ubuntu
        scp -o StrictHostKeyChecking=no -i secret.pem deploy_flask.sh ubuntu@15.207.110.45:/home/ubuntu
        scp -o StrictHostKeyChecking=no -i secret.pem check_app_status.sh ubuntu@15.207.110.45:/home/ubuntu
        
    - name: Connect to the instance and run the scripts
      run: |
        ssh -i secret.pem ubuntu@15.207.110.45 bash /home/ubuntu/deploy_flask.sh
        ssh -i secret.pem ubuntu@15.207.110.45 bash /home/ubuntu/check_app_status.sh